eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ec2-18-221-7-203.us-east-2.compute.amazonaws.com:8761/eureka/
  instance:
    hostname: localhost
